import json

recipes = [
    {
        "name": "Tomato Rasam",
        "category": "Soup",
        "ingredients": ["2 medium tomatoes chopped", "1 tsp rasam powder", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "2 cloves garlic crushed", "1 sprig curry leaves", "1/4 tsp turmeric", "1 tbsp tamarind paste", "2 cups water", "salt to taste", "fresh coriander for garnish"],
        "preparation": ["Boil tomatoes in water until soft and mash them well.", "In a small pan, heat oil and splutter mustard seeds and cumin seeds.", "Add crushed garlic and curry leaves, sauté briefly.", "Add rasam powder and turmeric, stir for 30 seconds.", "Pour the mashed tomato mixture and tamarind paste into the pan.", "Add 2 cups water, bring to a boil and simmer for 10 minutes.", "Season with salt and garnish with fresh coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 55,
        "protein": 2,
        "carbs": 10,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Classic South Indian comfort soup, perfect as an appetizer or with rice.",
        "videoUrl": ""
    },
    {
        "name": "Pepper Rasam",
        "category": "Soup",
        "ingredients": ["1 tbsp black peppercorns coarsely ground", "1 tsp cumin seeds", "2 medium tomatoes chopped", "1 tbsp tamarind paste", "2 cloves garlic", "1 sprig curry leaves", "1/2 tsp mustard seeds", "1/4 tsp turmeric", "1/4 tsp asafoetida", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Dry roast peppercorns and half the cumin seeds, then grind coarsely.", "Boil tomatoes in water until soft, then mash.", "In a pan, heat oil and splutter mustard seeds and remaining cumin seeds.", "Add curry leaves, garlic and asafoetida.", "Add the mashed tomato mixture, tamarind paste and turmeric.", "Stir in the ground pepper-cumin mixture.", "Simmer for 8-10 minutes, season with salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 50,
        "protein": 2,
        "carbs": 8,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Spicy pepper rasam is excellent for clearing congestion and boosting immunity.",
        "videoUrl": ""
    },
    {
        "name": "Garlic Rasam",
        "category": "Soup",
        "ingredients": ["8-10 garlic cloves crushed", "2 medium tomatoes chopped", "1 tsp rasam powder", "1 tbsp tamarind paste", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "1 sprig curry leaves", "1/4 tsp turmeric", "1 dried red chilli", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Boil tomatoes in water until soft and mash them.", "In a pan, heat oil and splutter mustard seeds and cumin seeds.", "Add crushed garlic cloves and sauté until lightly golden.", "Add curry leaves, dried red chilli and turmeric.", "Pour in the mashed tomato mixture and tamarind paste.", "Add rasam powder and simmer for 10 minutes.", "Season with salt and garnish with coriander leaves."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 60,
        "protein": 2,
        "carbs": 10,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Garlic rasam is a traditional remedy for cold and flu in South India.",
        "videoUrl": ""
    },
    {
        "name": "Lemon Rasam",
        "category": "Soup",
        "ingredients": ["2 tbsp fresh lemon juice", "1 medium tomato chopped", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "1 sprig curry leaves", "2 cloves garlic", "1/4 tsp turmeric", "1 tsp rasam powder", "1/4 tsp asafoetida", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Boil tomato in water until soft and mash.", "In a pan, heat oil and splutter mustard seeds and cumin seeds.", "Add garlic, curry leaves and asafoetida.", "Add turmeric and rasam powder, stir briefly.", "Pour in the mashed tomato mixture and simmer for 8 minutes.", "Remove from heat and stir in fresh lemon juice.", "Season with salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 45,
        "protein": 1,
        "carbs": 8,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Tangy and refreshing, lemon rasam aids digestion and is best served warm.",
        "videoUrl": ""
    },
    {
        "name": "Pineapple Rasam",
        "category": "Soup",
        "ingredients": ["1/2 cup pineapple finely chopped", "1 medium tomato chopped", "1 tsp rasam powder", "1 tbsp tamarind paste", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "1 sprig curry leaves", "1/4 tsp turmeric", "1 dried red chilli", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Cook pineapple pieces in water until softened.", "In another pot, boil and mash the tomato.", "Combine pineapple and tomato mixtures.", "In a pan, heat oil and splutter mustard seeds and cumin seeds.", "Add curry leaves, dried red chilli and turmeric.", "Pour in the combined fruit-tomato mixture and tamarind paste.", "Add rasam powder, simmer for 10 minutes, season and garnish."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 65,
        "protein": 1,
        "carbs": 14,
        "fat": 1,
        "isVegetarian": True,
        "notes": "A sweet-tangy rasam variation popular in Kerala and Tamil Nadu.",
        "videoUrl": ""
    },
    {
        "name": "Jeera Rasam",
        "category": "Soup",
        "ingredients": ["1 tbsp cumin seeds", "2 medium tomatoes chopped", "1 tbsp tamarind paste", "4 cloves garlic", "1/2 tsp black pepper", "1/4 tsp turmeric", "1/2 tsp mustard seeds", "1 sprig curry leaves", "1/4 tsp asafoetida", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Dry roast cumin seeds until aromatic, then grind to a coarse powder.", "Boil tomatoes in water until soft and mash.", "In a pan, heat oil and splutter mustard seeds.", "Add garlic, curry leaves and asafoetida.", "Add the mashed tomato, tamarind paste and turmeric.", "Stir in the roasted cumin powder and black pepper.", "Simmer for 8 minutes, season with salt and garnish."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 55,
        "protein": 2,
        "carbs": 9,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Cumin-forward rasam that helps with digestion and bloating.",
        "videoUrl": ""
    },
    {
        "name": "Mysore Rasam",
        "category": "Soup",
        "ingredients": ["2 medium tomatoes chopped", "1/4 cup toor dal cooked", "1 tbsp coconut grated", "2 dried red chillies", "1 tsp coriander seeds", "1/2 tsp cumin seeds", "1/2 tsp mustard seeds", "1 tbsp tamarind paste", "1/4 tsp turmeric", "1 sprig curry leaves", "2 cups water", "salt to taste"],
        "preparation": ["Dry roast coriander seeds, dried red chillies, and half the cumin with coconut.", "Grind roasted spices into a fine paste with a little water.", "Boil tomatoes in water until soft and mash.", "Combine mashed tomato, cooked toor dal and the ground paste.", "In a pan, heat oil and splutter mustard seeds and remaining cumin.", "Add curry leaves and pour in the rasam mixture.", "Add tamarind paste, turmeric and simmer for 12 minutes. Season with salt."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 80,
        "protein": 4,
        "carbs": 12,
        "fat": 2,
        "isVegetarian": True,
        "notes": "A richer, spicier rasam from Mysore with a coconut-spice paste base.",
        "videoUrl": ""
    },
    {
        "name": "Milagu Rasam",
        "category": "Soup",
        "ingredients": ["1.5 tbsp black peppercorns", "1 tsp cumin seeds", "3 cloves garlic", "2 medium tomatoes chopped", "1 tbsp tamarind paste", "1/2 tsp mustard seeds", "1 sprig curry leaves", "1/4 tsp turmeric", "1/4 tsp asafoetida", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Coarsely grind peppercorns, cumin seeds and garlic together.", "Boil tomatoes in water until soft and mash.", "In a pan, heat oil and splutter mustard seeds.", "Add curry leaves and asafoetida.", "Pour in the mashed tomato mixture and turmeric.", "Add the ground pepper-cumin-garlic mixture and tamarind paste.", "Simmer for 10 minutes, season and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 52,
        "protein": 2,
        "carbs": 8,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Milagu means pepper in Tamil. Extra peppery rasam for cold relief.",
        "videoUrl": ""
    },
    {
        "name": "Tamarind Rasam",
        "category": "Soup",
        "ingredients": ["2 tbsp tamarind paste", "2 medium tomatoes chopped", "1 tsp rasam powder", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "1 sprig curry leaves", "2 cloves garlic", "1/4 tsp turmeric", "1/4 tsp asafoetida", "1 dried red chilli", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Soak tamarind paste in warm water and extract the juice.", "Boil tomatoes in water until soft and mash.", "Combine tamarind water and mashed tomatoes.", "In a pan, heat oil and splutter mustard seeds and cumin seeds.", "Add garlic, curry leaves, dried red chilli and asafoetida.", "Pour in the tamarind-tomato mixture, add rasam powder and turmeric.", "Simmer for 10-12 minutes until flavors meld. Season and garnish."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 50,
        "protein": 1,
        "carbs": 10,
        "fat": 1,
        "isVegetarian": True,
        "notes": "The tangiest of all rasams, pairs beautifully with steamed rice.",
        "videoUrl": ""
    },
    {
        "name": "Neem Flower Rasam",
        "category": "Soup",
        "ingredients": ["1 tbsp fresh neem flowers", "2 medium tomatoes chopped", "1 tsp rasam powder", "1/2 tsp tamarind paste", "1/2 tsp mustard seeds", "1/2 tsp cumin seeds", "1 sprig curry leaves", "1/4 tsp turmeric", "1/4 tsp jaggery", "2 cups water", "salt to taste"],
        "preparation": ["Wash neem flowers thoroughly and set aside.", "Boil tomatoes in water until soft and mash.", "In a pan, heat oil and splutter mustard seeds and cumin seeds.", "Add curry leaves and neem flowers, sauté for 1 minute.", "Add turmeric and rasam powder.", "Pour in the mashed tomato mixture and tamarind paste.", "Add jaggery to balance bitterness. Simmer for 8 minutes and season."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 48,
        "protein": 2,
        "carbs": 9,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Traditional Ugadi recipe. Neem flowers are believed to purify blood.",
        "videoUrl": ""
    },
    {
        "name": "Tamatar Ka Shorba",
        "category": "Soup",
        "ingredients": ["4 medium tomatoes chopped", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1 tsp cumin seeds", "2 cloves", "1 small bay leaf", "1/2 tsp sugar", "1/2 tsp black pepper", "1 tbsp butter", "2 cups water", "salt to taste", "cream for garnish"],
        "preparation": ["Heat butter in a pot and add cumin seeds, cloves and bay leaf.", "Add onion, garlic and ginger, sauté until golden.", "Add chopped tomatoes and cook until completely soft.", "Add water and simmer for 15 minutes.", "Remove bay leaf and cloves, blend the mixture until smooth.", "Strain through a sieve for a silky texture.", "Season with salt, pepper and sugar. Serve with a swirl of cream."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 90,
        "protein": 2,
        "carbs": 12,
        "fat": 4,
        "isVegetarian": True,
        "notes": "North Indian tomato soup, richer and creamier than rasam.",
        "videoUrl": ""
    },
    {
        "name": "Palak Shorba",
        "category": "Soup",
        "ingredients": ["2 cups fresh spinach leaves", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1 green chilli", "1/2 tsp cumin seeds", "1/2 tsp garam masala", "1 tbsp butter", "2 cups water", "salt to taste", "black pepper", "lemon juice"],
        "preparation": ["Blanch spinach leaves in boiling water for 2 minutes, then ice bath.", "Heat butter in a pot and add cumin seeds.", "Sauté onion, garlic, ginger and green chilli until soft.", "Add blanched spinach and cook for 2 minutes.", "Add water and simmer for 10 minutes.", "Blend until smooth and return to the pot.", "Season with garam masala, salt, pepper and a squeeze of lemon."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 75,
        "protein": 4,
        "carbs": 8,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Iron-rich spinach soup, great for boosting hemoglobin levels.",
        "videoUrl": ""
    },
    {
        "name": "Dal Shorba",
        "category": "Soup",
        "ingredients": ["1/2 cup masoor dal washed", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp ghee", "3 cups water", "salt to taste", "coriander leaves", "lemon juice"],
        "preparation": ["Pressure cook masoor dal with turmeric and water for 3 whistles.", "Heat ghee in a pan and add cumin seeds.", "Sauté onion, garlic and ginger until golden.", "Add chopped tomato and cook until soft.", "Add the cooked dal and mix well.", "Simmer for 10 minutes, add garam masala.", "Season with salt and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 120,
        "protein": 7,
        "carbs": 16,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Protein-rich lentil soup, a staple in North Indian households.",
        "videoUrl": ""
    },
    {
        "name": "Gosht Shorba Light",
        "category": "Soup",
        "ingredients": ["200g mutton bones with some meat", "1 small onion sliced", "2 cloves garlic", "1 inch ginger", "2 green cardamom", "1 small cinnamon stick", "2 cloves", "1 bay leaf", "1/2 tsp black pepper", "1/4 tsp turmeric", "4 cups water", "salt to taste", "coriander leaves", "lemon juice"],
        "preparation": ["Wash mutton bones thoroughly.", "In a pressure cooker, add bones, onion, garlic, ginger and all whole spices.", "Add turmeric, salt and water.", "Pressure cook for 5-6 whistles until meat is tender.", "Strain the broth through a fine sieve.", "Return broth to pot and simmer to reduce slightly.", "Season with pepper and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 3,
        "calories": 110,
        "protein": 12,
        "carbs": 3,
        "fat": 5,
        "isVegetarian": False,
        "notes": "Traditional Mughlai bone broth, believed to be restorative and warming.",
        "videoUrl": ""
    },
    {
        "name": "Murgh Shorba Light",
        "category": "Soup",
        "ingredients": ["200g chicken with bones", "1 small onion sliced", "2 cloves garlic", "1 inch ginger", "2 green cardamom", "1 small cinnamon stick", "2 cloves", "1 bay leaf", "1/2 tsp black pepper", "1/4 tsp turmeric", "1 green chilli", "4 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Clean chicken pieces and wash thoroughly.", "In a pot, combine chicken, onion, garlic, ginger and whole spices.", "Add turmeric, green chilli and water.", "Bring to a boil, skim off any foam.", "Simmer on low heat for 30-35 minutes.", "Strain the broth and shred some chicken for serving.", "Season with salt and pepper. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 3,
        "calories": 100,
        "protein": 14,
        "carbs": 2,
        "fat": 4,
        "isVegetarian": False,
        "notes": "Light chicken shorba is a classic Mughlai starter for festive meals.",
        "videoUrl": ""
    },
    {
        "name": "Mulligatawny Soup",
        "category": "Soup",
        "ingredients": ["1/4 cup toor dal", "1 small onion chopped", "1 medium tomato chopped", "1 small carrot diced", "1 small apple peeled and diced", "2 cloves garlic", "1 inch ginger", "1 tsp curry powder", "1/2 tsp cumin", "1/4 tsp turmeric", "1 tbsp coconut milk", "1 tbsp oil", "3 cups water", "salt to taste", "lemon juice"],
        "preparation": ["Cook toor dal until soft with turmeric.", "Heat oil in a pot and sauté onion, garlic and ginger until golden.", "Add carrot and apple, cook for 3 minutes.", "Add curry powder and cumin, stir well.", "Add chopped tomato and cook until soft.", "Add cooked dal and water, simmer for 15 minutes.", "Blend partially, stir in coconut milk. Season with salt and lemon juice."],
        "servingSize": "1 bowl",
        "servings": 3,
        "calories": 110,
        "protein": 5,
        "carbs": 16,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Anglo-Indian soup with origins in Tamil Nadu, meaning pepper water.",
        "videoUrl": ""
    },
    {
        "name": "Mulligatawny Veg",
        "category": "Soup",
        "ingredients": ["1/4 cup moong dal", "1 small onion chopped", "1 medium tomato chopped", "1 small carrot diced", "1/4 cup peas", "2 cloves garlic", "1 inch ginger", "1 tsp curry powder", "1/2 tsp cumin", "1/4 tsp turmeric", "1 tbsp coconut cream", "1 tbsp oil", "3 cups water", "salt to taste"],
        "preparation": ["Cook moong dal until soft with turmeric.", "Heat oil and sauté onion, garlic and ginger.", "Add carrot and peas, cook for 3 minutes.", "Add curry powder and cumin.", "Add tomato and cook until mushy.", "Add cooked dal and water, simmer for 12 minutes.", "Blend half the soup for texture. Stir in coconut cream and season."],
        "servingSize": "1 bowl",
        "servings": 3,
        "calories": 105,
        "protein": 5,
        "carbs": 15,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Pure vegetarian version of the classic mulligatawny with mixed vegetables.",
        "videoUrl": ""
    },
    {
        "name": "Spicy Mulligatawny",
        "category": "Soup",
        "ingredients": ["1/4 cup masoor dal", "1 small onion chopped", "1 medium tomato chopped", "2 green chillies", "2 cloves garlic", "1 inch ginger", "1.5 tsp curry powder", "1/2 tsp red chilli powder", "1/2 tsp cumin", "1/4 tsp turmeric", "1 tbsp oil", "3 cups water", "salt to taste", "lemon juice", "coriander leaves"],
        "preparation": ["Cook masoor dal until soft with turmeric.", "Heat oil and sauté onion, garlic, ginger and green chillies.", "Add curry powder, red chilli powder and cumin, stir.", "Add tomato and cook until pulpy.", "Add cooked dal and water, simmer for 15 minutes.", "Blend until smooth and return to pot.", "Season with salt and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 115,
        "protein": 6,
        "carbs": 16,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Extra spicy version for those who love heat in their soups.",
        "videoUrl": ""
    },
    {
        "name": "Coconut Mulligatawny",
        "category": "Soup",
        "ingredients": ["1/4 cup toor dal", "1 small onion chopped", "1 medium tomato chopped", "1/4 cup coconut milk", "2 cloves garlic", "1 inch ginger", "1 tsp curry powder", "1/2 tsp cumin", "1/4 tsp turmeric", "1 tbsp coconut oil", "3 cups water", "salt to taste", "curry leaves"],
        "preparation": ["Cook toor dal until soft with turmeric.", "Heat coconut oil and sauté onion, garlic and ginger.", "Add curry leaves, curry powder and cumin.", "Add tomato and cook until soft.", "Add cooked dal and water, simmer for 12 minutes.", "Blend until smooth and return to pot.", "Stir in coconut milk, heat gently. Season with salt."],
        "servingSize": "1 bowl",
        "servings": 3,
        "calories": 125,
        "protein": 5,
        "carbs": 14,
        "fat": 6,
        "isVegetarian": True,
        "notes": "Creamy coconut version with a rich South Indian flavor profile.",
        "videoUrl": ""
    },
    {
        "name": "Lemon Coriander Soup",
        "category": "Soup",
        "ingredients": ["1 cup mixed vegetables finely chopped", "1/4 cup fresh coriander leaves chopped", "2 tbsp lemon juice", "1 small onion chopped", "2 cloves garlic minced", "1 inch ginger grated", "1 tbsp cornstarch", "1/2 tsp black pepper", "2 cups vegetable stock", "1 tbsp oil", "salt to taste"],
        "preparation": ["Heat oil in a pot and sauté onion, garlic and ginger.", "Add finely chopped mixed vegetables and cook for 3 minutes.", "Pour in vegetable stock and bring to a boil.", "Simmer for 10 minutes until vegetables are tender.", "Mix cornstarch with 2 tbsp water and stir into the soup.", "Cook until slightly thickened.", "Add lemon juice, coriander and pepper. Season with salt."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 70,
        "protein": 2,
        "carbs": 11,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Light and refreshing Indo-Chinese style soup popular in restaurants.",
        "videoUrl": ""
    },
    {
        "name": "Lemon Ginger Soup",
        "category": "Soup",
        "ingredients": ["2 inch ginger grated", "2 tbsp lemon juice", "1 small onion chopped", "2 cloves garlic", "1 medium carrot diced", "1 stalk celery chopped", "1/2 tsp black pepper", "1/2 tsp turmeric", "2 cups water", "1 tsp honey", "1 tbsp oil", "salt to taste"],
        "preparation": ["Heat oil and sauté onion and garlic until soft.", "Add grated ginger and cook for 1 minute.", "Add carrot and celery, cook for 3 minutes.", "Pour in water and turmeric, bring to a boil.", "Simmer for 12 minutes until vegetables are tender.", "Blend until smooth and return to pot.", "Add lemon juice, honey and pepper. Season with salt."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 65,
        "protein": 1,
        "carbs": 12,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Warming soup that soothes sore throats and boosts immunity.",
        "videoUrl": ""
    },
    {
        "name": "Lemon Pepper Soup Indian",
        "category": "Soup",
        "ingredients": ["1 tbsp crushed black pepper", "2 tbsp lemon juice", "1 small onion chopped", "2 cloves garlic", "1 medium tomato chopped", "1/2 tsp cumin powder", "1/4 tsp turmeric", "1 tbsp cornstarch", "2 cups vegetable stock", "1 tbsp butter", "salt to taste", "coriander leaves"],
        "preparation": ["Heat butter and sauté onion and garlic until translucent.", "Add tomato and cook until soft.", "Pour in vegetable stock and bring to a boil.", "Add turmeric and cumin powder, simmer for 10 minutes.", "Blend until smooth and strain back into the pot.", "Mix cornstarch with water and stir in to thicken.", "Add crushed pepper and lemon juice. Season and garnish."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 72,
        "protein": 2,
        "carbs": 10,
        "fat": 3,
        "isVegetarian": True,
        "notes": "A zesty, peppery soup that works as a great cold-weather appetizer.",
        "videoUrl": ""
    },
    {
        "name": "Mixed Vegetable Soup Indian",
        "category": "Soup",
        "ingredients": ["1/4 cup carrot diced", "1/4 cup beans chopped", "1/4 cup peas", "1/4 cup potato diced", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin powder", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp butter", "2 cups water", "salt to taste", "pepper"],
        "preparation": ["Heat butter and sauté onion, garlic and ginger until soft.", "Add all chopped vegetables and stir for 2 minutes.", "Add tomato, turmeric and cumin powder.", "Pour in water and bring to a boil.", "Simmer for 15 minutes until all vegetables are tender.", "Blend half the soup for a chunky texture.", "Add garam masala, salt and pepper. Serve hot."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 85,
        "protein": 3,
        "carbs": 14,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Wholesome mixed vegetable soup with Indian spices, perfect for light meals.",
        "videoUrl": ""
    },
    {
        "name": "Clear Veg Soup Indian",
        "category": "Soup",
        "ingredients": ["1/4 cup carrot julienned", "1/4 cup cabbage shredded", "1/4 cup beans finely chopped", "2-3 mushrooms sliced", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp black pepper", "1 tsp soy sauce", "2 cups vegetable stock", "1 tsp oil", "salt to taste", "spring onions"],
        "preparation": ["Heat oil in a pot and sauté onion, garlic and ginger briefly.", "Add vegetable stock and bring to a boil.", "Add all the julienned and chopped vegetables.", "Simmer for 8-10 minutes keeping vegetables slightly crunchy.", "Add soy sauce and black pepper.", "Season with salt to taste.", "Serve hot garnished with spring onions."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 45,
        "protein": 2,
        "carbs": 7,
        "fat": 1,
        "isVegetarian": True,
        "notes": "Low-calorie clear broth with crisp vegetables, ideal for weight watchers.",
        "videoUrl": ""
    },
    {
        "name": "Thick Veg Soup Indian",
        "category": "Soup",
        "ingredients": ["1/4 cup carrot diced", "1/4 cup potato diced", "1/4 cup cauliflower florets", "1/4 cup peas", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin powder", "1 tbsp cornstarch", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "cream optional"],
        "preparation": ["Heat butter and sauté onion, garlic and ginger.", "Add all vegetables and stir for 2 minutes.", "Add water and cumin powder, bring to a boil.", "Simmer for 15 minutes until vegetables are completely soft.", "Blend until smooth and return to pot.", "Mix cornstarch with water and stir in.", "Cook until thick and creamy. Season with salt and pepper."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 95,
        "protein": 3,
        "carbs": 14,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Thick and creamy vegetable soup without heavy cream, naturally thickened.",
        "videoUrl": ""
    },
    {
        "name": "Tomato Soup Indian",
        "category": "Soup",
        "ingredients": ["4 medium ripe tomatoes chopped", "1 small onion chopped", "2 cloves garlic", "1/2 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp sugar", "1 tbsp butter", "1/2 tsp black pepper", "2 cups water", "salt to taste", "cream for garnish", "croutons optional"],
        "preparation": ["Heat butter and add cumin seeds until they splutter.", "Sauté onion, garlic and ginger until golden.", "Add chopped tomatoes and cook until completely mushy.", "Add turmeric and water, simmer for 15 minutes.", "Blend until smooth and strain for a silky texture.", "Return to pot and add sugar to balance acidity.", "Season with salt and pepper. Serve with cream and croutons."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 85,
        "protein": 2,
        "carbs": 12,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Beloved Indian-style tomato soup, a rainy day comfort classic.",
        "videoUrl": ""
    },
    {
        "name": "Roasted Tomato Soup Indian",
        "category": "Soup",
        "ingredients": ["5 medium tomatoes halved", "1 small onion quartered", "4 cloves garlic", "1 tbsp oil", "1/2 tsp cumin powder", "1/2 tsp red chilli flakes", "1/4 tsp sugar", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "basil leaves"],
        "preparation": ["Preheat oven to 200°C. Place tomatoes, onion and garlic on a tray.", "Drizzle with oil and roast for 25 minutes until charred.", "Transfer roasted vegetables to a pot.", "Add water, cumin powder and bring to a boil.", "Simmer for 10 minutes and blend until smooth.", "Stir in butter and sugar.", "Season with salt, pepper and chilli flakes. Garnish with basil."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 95,
        "protein": 2,
        "carbs": 12,
        "fat": 5,
        "isVegetarian": True,
        "notes": "Roasting intensifies the tomato flavor and adds a smoky depth.",
        "videoUrl": ""
    },
    {
        "name": "Tomato Basil Indian",
        "category": "Soup",
        "ingredients": ["4 medium tomatoes chopped", "1 small onion chopped", "2 cloves garlic", "1/4 cup fresh basil leaves", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp sugar", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "cream optional"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion and garlic until soft.", "Add tomatoes and cook until pulpy.", "Add turmeric, water and simmer for 15 minutes.", "Add fresh basil leaves and cook for 2 more minutes.", "Blend until smooth and strain.", "Season with sugar, salt and pepper. Serve hot."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 80,
        "protein": 2,
        "carbs": 11,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Indian twist on tomato basil with cumin and turmeric undertones.",
        "videoUrl": ""
    },
    {
        "name": "Spinach Soup Indian",
        "category": "Soup",
        "ingredients": ["3 cups fresh spinach", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1 green chilli", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/4 tsp garam masala", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "lemon juice"],
        "preparation": ["Blanch spinach in boiling water for 2 minutes and drain.", "Heat butter and add cumin seeds.", "Sauté onion, garlic, ginger and green chilli.", "Add blanched spinach and turmeric, cook for 2 minutes.", "Add water and simmer for 10 minutes.", "Blend until smooth and return to pot.", "Add garam masala, salt, pepper and lemon juice. Serve hot."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 70,
        "protein": 4,
        "carbs": 7,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Rich in iron and vitamins, a nutritious soup for everyday meals.",
        "videoUrl": ""
    },
    {
        "name": "Palak Soup Creamy",
        "category": "Soup",
        "ingredients": ["3 cups fresh spinach", "1 small onion chopped", "1 medium potato diced", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp nutmeg", "2 tbsp cream", "1 tbsp butter", "2 cups water", "salt to taste", "pepper"],
        "preparation": ["Blanch spinach and set aside.", "Heat butter and add cumin seeds.", "Sauté onion, garlic and ginger until soft.", "Add diced potato and cook for 3 minutes.", "Add water and cook until potato is completely tender.", "Add blanched spinach and cook for 2 minutes.", "Blend until smooth, stir in cream and nutmeg. Season with salt and pepper."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 105,
        "protein": 4,
        "carbs": 12,
        "fat": 5,
        "isVegetarian": True,
        "notes": "Potato adds natural creaminess to this spinach soup without heavy cream.",
        "videoUrl": ""
    },
    {
        "name": "Spinach Moong Soup",
        "category": "Soup",
        "ingredients": ["2 cups fresh spinach", "1/4 cup yellow moong dal", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp ghee", "3 cups water", "salt to taste", "lemon juice"],
        "preparation": ["Wash moong dal and cook with turmeric until soft.", "Blanch spinach separately.", "Heat ghee and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add cooked dal and blanched spinach.", "Add remaining water and simmer for 10 minutes.", "Blend partially, add garam masala, salt and lemon juice."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 110,
        "protein": 7,
        "carbs": 14,
        "fat": 3,
        "isVegetarian": True,
        "notes": "High-protein soup combining spinach and lentils for a balanced meal.",
        "videoUrl": ""
    },
    {
        "name": "Carrot Soup Indian",
        "category": "Soup",
        "ingredients": ["3 medium carrots diced", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/4 tsp cinnamon", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "cream optional"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion, garlic and ginger until golden.", "Add diced carrots and cook for 3 minutes.", "Add turmeric, cinnamon and water.", "Bring to a boil and simmer for 15 minutes until carrots are tender.", "Blend until smooth and return to pot.", "Season with salt and pepper. Serve with a drizzle of cream."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 80,
        "protein": 2,
        "carbs": 13,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Naturally sweet carrot soup with warm Indian spices.",
        "videoUrl": ""
    },
    {
        "name": "Carrot Ginger Indian Soup",
        "category": "Soup",
        "ingredients": ["3 medium carrots diced", "2 inch ginger grated", "1 small onion chopped", "2 cloves garlic", "1/2 tsp cumin powder", "1/4 tsp turmeric", "1/4 tsp red chilli flakes", "1 tbsp oil", "2 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Heat oil and sauté onion, garlic and ginger until fragrant.", "Add diced carrots and cook for 2 minutes.", "Add cumin powder, turmeric and water.", "Bring to a boil and simmer for 15 minutes.", "Blend until smooth and return to pot.", "Add chilli flakes and season with salt.", "Serve hot garnished with coriander leaves."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 75,
        "protein": 2,
        "carbs": 12,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Ginger adds a warming kick that pairs perfectly with sweet carrots.",
        "videoUrl": ""
    },
    {
        "name": "Carrot Coriander Indian",
        "category": "Soup",
        "ingredients": ["3 medium carrots diced", "1/2 cup fresh coriander leaves", "1 small onion chopped", "2 cloves garlic", "1/2 tsp coriander powder", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "lemon juice"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion and garlic until soft.", "Add carrots and coriander powder, cook for 2 minutes.", "Add turmeric and water, bring to a boil.", "Simmer for 15 minutes until carrots are tender.", "Add fresh coriander leaves and blend until smooth.", "Season with salt, pepper and lemon juice."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 78,
        "protein": 2,
        "carbs": 12,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Fresh coriander adds a bright, herbaceous flavor to sweet carrot soup.",
        "videoUrl": ""
    },
    {
        "name": "Beetroot Soup Indian",
        "category": "Soup",
        "ingredients": ["2 medium beetroots peeled and diced", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/4 tsp garam masala", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "yogurt for garnish"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add diced beetroot and cook for 3 minutes.", "Add turmeric and water, bring to a boil.", "Simmer for 20 minutes until beetroot is tender.", "Blend until smooth and return to pot.", "Add garam masala, salt and pepper. Serve with a dollop of yogurt."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 85,
        "protein": 3,
        "carbs": 14,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Vibrant ruby-red soup rich in iron and antioxidants.",
        "videoUrl": ""
    },
    {
        "name": "Beetroot Ginger Soup",
        "category": "Soup",
        "ingredients": ["2 medium beetroots peeled and diced", "2 inch ginger grated", "1 small onion chopped", "2 cloves garlic", "1/2 tsp cumin powder", "1/4 tsp black pepper", "1 tsp lemon juice", "1 tbsp oil", "2 cups water", "salt to taste", "mint leaves"],
        "preparation": ["Heat oil and sauté onion, garlic and ginger.", "Add beetroot and cumin powder, stir for 2 minutes.", "Add water and bring to a boil.", "Simmer for 20 minutes until beetroot is soft.", "Blend until smooth and return to pot.", "Add black pepper and lemon juice.", "Season with salt and garnish with mint leaves."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 80,
        "protein": 2,
        "carbs": 14,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Ginger cuts through beetroot's earthy sweetness for a balanced flavor.",
        "videoUrl": ""
    },
    {
        "name": "Beetroot Carrot Soup Indian",
        "category": "Soup",
        "ingredients": ["1 medium beetroot peeled and diced", "2 medium carrots diced", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "cream optional"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add beetroot and carrots, cook for 3 minutes.", "Add turmeric and water, bring to a boil.", "Simmer for 20 minutes until vegetables are tender.", "Blend until smooth and return to pot.", "Season with salt and pepper. Serve with cream if desired."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 82,
        "protein": 2,
        "carbs": 13,
        "fat": 3,
        "isVegetarian": True,
        "notes": "A beautiful two-toned root vegetable soup packed with nutrients.",
        "videoUrl": ""
    },
    {
        "name": "Sweet Corn Soup Indian",
        "category": "Soup",
        "ingredients": ["1 cup sweet corn kernels", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp black pepper", "1 tbsp cornstarch", "1 tsp soy sauce", "1 tsp vinegar", "1 tbsp oil", "2 cups vegetable stock", "salt to taste", "spring onions"],
        "preparation": ["Boil half the corn kernels and blend into a puree.", "Heat oil and sauté onion, garlic and ginger.", "Add corn puree and remaining whole kernels.", "Pour in vegetable stock and bring to a boil.", "Mix cornstarch with water and stir into the soup.", "Add soy sauce and vinegar, cook until thickened.", "Season with salt and pepper. Garnish with spring onions."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 110,
        "protein": 3,
        "carbs": 20,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Indo-Chinese sweet corn soup, a favorite street food appetizer.",
        "videoUrl": ""
    },
    {
        "name": "Corn Spinach Soup",
        "category": "Soup",
        "ingredients": ["1 cup sweet corn kernels", "1 cup spinach chopped", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin powder", "1 tbsp cornstarch", "1 tbsp butter", "2 cups water", "salt to taste", "pepper", "cream optional"],
        "preparation": ["Boil corn kernels and blend half into a puree.", "Blanch spinach briefly.", "Heat butter and sauté onion, garlic and ginger.", "Add corn puree, whole corn and blanched spinach.", "Add water and cumin powder, simmer for 10 minutes.", "Mix cornstarch with water and stir in to thicken.", "Season with salt and pepper. Serve hot."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 100,
        "protein": 4,
        "carbs": 17,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Nutritious combination of iron-rich spinach and fiber-rich corn.",
        "videoUrl": ""
    },
    {
        "name": "Corn Pepper Soup Indian",
        "category": "Soup",
        "ingredients": ["1 cup sweet corn kernels", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1 tsp crushed black pepper", "1 green chilli chopped", "1 tbsp cornstarch", "1 tsp soy sauce", "1 tbsp oil", "2 cups vegetable stock", "salt to taste", "coriander leaves"],
        "preparation": ["Boil half the corn and blend to a puree.", "Heat oil and sauté onion, garlic, ginger and green chilli.", "Add corn puree and whole kernels.", "Pour in stock and bring to a boil.", "Mix cornstarch with water and stir in.", "Add soy sauce and crushed black pepper.", "Cook until thick. Season with salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 105,
        "protein": 3,
        "carbs": 18,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Peppery corn soup with a satisfying kick, restaurant-style preparation.",
        "videoUrl": ""
    },
    {
        "name": "Moong Dal Soup",
        "category": "Soup",
        "ingredients": ["1/2 cup yellow moong dal", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp ghee", "3 cups water", "salt to taste", "lemon juice", "coriander leaves"],
        "preparation": ["Wash and cook moong dal with turmeric until soft.", "Heat ghee and add cumin seeds.", "Sauté onion, garlic and ginger until golden.", "Add tomato and cook until soft.", "Add cooked dal and remaining water.", "Simmer for 10 minutes and blend until smooth.", "Add garam masala, salt and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 120,
        "protein": 8,
        "carbs": 17,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Light and easily digestible lentil soup, great for recovery meals.",
        "videoUrl": ""
    },
    {
        "name": "Masoor Dal Soup",
        "category": "Soup",
        "ingredients": ["1/2 cup masoor dal red lentils", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp red chilli powder", "1 tbsp oil", "3 cups water", "salt to taste", "lemon juice", "coriander leaves"],
        "preparation": ["Wash masoor dal and cook with turmeric until soft.", "Heat oil and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add tomato and cook until mushy.", "Add cooked dal and water, stir well.", "Simmer for 10 minutes, add red chilli powder.", "Season with salt and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 125,
        "protein": 8,
        "carbs": 18,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Red lentil soup cooks quickly and has a naturally creamy texture.",
        "videoUrl": ""
    },
    {
        "name": "Mixed Dal Soup",
        "category": "Soup",
        "ingredients": ["2 tbsp moong dal", "2 tbsp masoor dal", "2 tbsp toor dal", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp ghee", "3 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Wash all dals together and cook with turmeric until soft.", "Heat ghee and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add tomato and cook until pulpy.", "Add cooked mixed dal and water.", "Simmer for 12 minutes, blend partially.", "Add garam masala and salt. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 130,
        "protein": 9,
        "carbs": 18,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Three lentils combined for a well-rounded protein profile.",
        "videoUrl": ""
    },
    {
        "name": "Toor Dal Soup",
        "category": "Soup",
        "ingredients": ["1/2 cup toor dal", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp sambhar powder", "1 tbsp ghee", "3 cups water", "salt to taste", "curry leaves", "coriander leaves"],
        "preparation": ["Wash toor dal and pressure cook with turmeric for 3 whistles.", "Heat ghee and add cumin seeds and curry leaves.", "Sauté onion, garlic and ginger.", "Add tomato and cook until soft.", "Add cooked dal and water, mix well.", "Add sambhar powder and simmer for 10 minutes.", "Season with salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 125,
        "protein": 8,
        "carbs": 18,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Toor dal has a nutty flavor that makes a satisfying everyday soup.",
        "videoUrl": ""
    },
    {
        "name": "Chana Dal Soup",
        "category": "Soup",
        "ingredients": ["1/2 cup chana dal soaked 30 min", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 green chilli", "1 tbsp ghee", "3 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Pressure cook soaked chana dal with turmeric for 4 whistles.", "Heat ghee and add cumin seeds.", "Sauté onion, garlic, ginger and green chilli.", "Add tomato and cook until soft.", "Add cooked chana dal and water.", "Simmer for 12 minutes and blend until smooth.", "Add garam masala, salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 135,
        "protein": 8,
        "carbs": 20,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Hearty chana dal soup with a slightly nutty flavor profile.",
        "videoUrl": ""
    },
    {
        "name": "Green Gram Soup",
        "category": "Soup",
        "ingredients": ["1/2 cup whole green moong soaked", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp coriander powder", "1 tbsp oil", "3 cups water", "salt to taste", "lemon juice", "coriander leaves"],
        "preparation": ["Cook soaked green moong with turmeric until soft.", "Heat oil and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add tomato and coriander powder, cook until soft.", "Add cooked green gram and water.", "Simmer for 10 minutes, partially blend.", "Season with salt and lemon juice. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 115,
        "protein": 8,
        "carbs": 16,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Whole green gram retains more fiber than split moong dal.",
        "videoUrl": ""
    },
    {
        "name": "Urad Dal Soup Light",
        "category": "Soup",
        "ingredients": ["1/4 cup urad dal soaked", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/4 tsp asafoetida", "1/2 tsp garam masala", "1 tbsp ghee", "3 cups water", "salt to taste", "coriander leaves"],
        "preparation": ["Pressure cook soaked urad dal with turmeric until soft.", "Heat ghee and add cumin seeds and asafoetida.", "Sauté onion, garlic and ginger.", "Add tomato and cook until mushy.", "Add cooked urad dal and water.", "Simmer for 10 minutes, blend until smooth.", "Add garam masala, salt and garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 118,
        "protein": 7,
        "carbs": 15,
        "fat": 3,
        "isVegetarian": True,
        "notes": "Urad dal is rich in protein and iron, great for building strength.",
        "videoUrl": ""
    },
    {
        "name": "Bottle Gourd Soup Indian",
        "category": "Soup",
        "ingredients": ["1 medium bottle gourd peeled and diced", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/4 tsp black pepper", "1 tbsp butter", "2 cups water", "salt to taste", "mint leaves"],
        "preparation": ["Heat butter and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add diced bottle gourd and turmeric.", "Add water and bring to a boil.", "Simmer for 15 minutes until gourd is tender.", "Blend until smooth and return to pot.", "Season with salt and pepper. Garnish with mint."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 55,
        "protein": 2,
        "carbs": 8,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Very low-calorie soup, bottle gourd is cooling and aids weight loss.",
        "videoUrl": ""
    },
    {
        "name": "Lauki Soup",
        "category": "Soup",
        "ingredients": ["1 medium lauki peeled and chopped", "1 small onion chopped", "1 medium tomato chopped", "2 cloves garlic", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp garam masala", "1 tbsp oil", "2 cups water", "salt to taste", "pepper", "coriander leaves"],
        "preparation": ["Heat oil and add cumin seeds.", "Sauté onion and garlic until golden.", "Add lauki and tomato, stir for 2 minutes.", "Add turmeric and water, bring to a boil.", "Simmer for 15-18 minutes until lauki is very soft.", "Blend until smooth and return to pot.", "Add garam masala, salt and pepper. Garnish with coriander."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 60,
        "protein": 2,
        "carbs": 9,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Lauki soup is recommended in Ayurveda for its cooling properties.",
        "videoUrl": ""
    },
    {
        "name": "Dudhi Soup",
        "category": "Soup",
        "ingredients": ["1 medium dudhi peeled and diced", "1/4 cup moong dal", "1 small onion chopped", "2 cloves garlic", "1 inch ginger", "1/2 tsp cumin seeds", "1/4 tsp turmeric", "1/2 tsp coriander powder", "1 tbsp ghee", "3 cups water", "salt to taste", "lemon juice"],
        "preparation": ["Cook moong dal with turmeric until soft.", "Heat ghee and add cumin seeds.", "Sauté onion, garlic and ginger.", "Add diced dudhi and coriander powder.", "Add cooked dal and water, bring to a boil.", "Simmer for 15 minutes until dudhi is tender.", "Blend until smooth. Season with salt and lemon juice."],
        "servingSize": "1 bowl",
        "servings": 2,
        "calories": 90,
        "protein": 5,
        "carbs": 13,
        "fat": 2,
        "isVegetarian": True,
        "notes": "Dudhi with moong dal makes a protein-enriched light soup.",
        "videoUrl": ""
    }
]

with open("soup_batch1.json", "w") as f:
    json.dump(recipes, f, indent=2)
print(f"Batch 1: {len(recipes)} recipes written")