name: coresync
description: "A multi-module productivity app with TodoList, Password Manager, and Gym Tracker."
publish_to: 'none'
version: 1.1.0+15
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0

  # Routing
  go_router: ^14.8.1

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  path: ^1.9.0

  # Security
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  pointycastle: ^3.9.1

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

  # UI / Utilities
  table_calendar: ^3.2.0
  lottie: ^3.3.1
  intl: ^0.20.2
  uuid: ^4.5.1
  fl_chart: ^0.70.2
  equatable: ^2.0.7
  flutter_timezone: ^5.0.1
  firebase_messaging: ^15.2.10
  flutter_contacts: ^1.1.9+2
  pedometer_2: ^5.0.4
  flutter_activity_recognition: ^3.0.1
  permission_handler: ^11.3.1
  health: ^13.3.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.6
  flutter_doc_scanner: ^0.0.18
  pdf: ^3.11.1
  share_plus: ^10.1.4
  printing: ^5.13.4
  google_mlkit_text_recognition: ^0.15.1
  translator: ^1.0.0
  image_cropper: ^8.0.2
  image: ^4.5.2
  crypto: ^3.0.6
  mobile_scanner: ^7.0.0
  nfc_manager: ^3.5.0
  math_expressions: ^2.6.0
  url_launcher: ^6.3.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  local_auth: ^2.3.0
  video_player: ^2.11.1
  archive: ^4.0.4
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#1A1A2B"
    theme_color: "#1A1A2B"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 256
  linux:
    generate: true
    image_path: "assets/app_icon.png"

flutter_native_splash:
  background_image: "assets/splash_screen.jpg"
  fullscreen: true
  android: true
  ios: true
  web: true
  android_12:
    background_image: "assets/splash_screen.jpg"
    fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/splash_screen.jpg
    - assets/service-account.json
    - assets/lottie/exercises/
    - assets/videos/exercises/
    - assets/recipes/
    - assets/foods/
