// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_3AdOLRj0yCy7jmzQ5MVJNT2JQgZ6KoY',
    appId: '1:954417312512:web:f3bbcb678855eda73079e5',
    messagingSenderId: '954417312512',
    projectId: 'coresync-e7fb5',
    authDomain: 'coresync-e7fb5.firebaseapp.com',
    storageBucket: 'coresync-e7fb5.firebasestorage.app',
    measurementId: 'G-GKSMBKGH10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHCdbgJrhKau9OWs6pjflGFlc8oD3CtFs',
    appId: '1:954417312512:android:81fceb96075cf33f3079e5',
    messagingSenderId: '954417312512',
    projectId: 'coresync-e7fb5',
    storageBucket: 'coresync-e7fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0rVmDxtaSfGY7dEHac4kE6o3StlO920',
    appId: '1:954417312512:ios:a48f80c8b8ebf9523079e5',
    messagingSenderId: '954417312512',
    projectId: 'coresync-e7fb5',
    storageBucket: 'coresync-e7fb5.firebasestorage.app',
    iosBundleId: 'com.example.coresync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0rVmDxtaSfGY7dEHac4kE6o3StlO920',
    appId: '1:954417312512:ios:a48f80c8b8ebf9523079e5',
    messagingSenderId: '954417312512',
    projectId: 'coresync-e7fb5',
    storageBucket: 'coresync-e7fb5.firebasestorage.app',
    iosBundleId: 'com.example.coresync',
  );
}
